### ISSUE TITLE
replace circleci/buildpack-deps

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-tool-enonic-ci#10]
circleci/buildpack-deps docker image is not updated for 2 years. Find alternative base docker image.

**Comment by jsi** [comment]
We no longer use `circleci/buildpack-deps`, we only use `circleci/node`.  This has been replaced with `cimg/node`: https://hub.docker.com/r/cimg/node

We should test this when releasing XP 7.14 in December.  Comment about this has been added to the TRR minutes document.

**Comment by jsi** [comment]
A first 7.14 image has been built, based on B1.  It may be tested now.

**Comment by jsi** [comment]
Done in the 7.14.0 release.
