### ISSUE TITLE
Rename Github repository to enonic-ci

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-tool-enonic-ci#6]
`enonic-ci` is more generic - it won't be confusigf to put GA code in such repository https://github.com/enonic/enonic-ci-image/issues/2

**Comment by rymsha** [comment]
Note, that documentation reference must be updated

**Comment by jsi** [comment]
According to the procedure for naming repos, the name of the repo should be xp-tool-enonic-ci: https://enonic.atlassian.net/wiki/spaces/ISO/pages/2316271617/Procedure+-+Creating+and+naming+code+repos

**Comment by jsi** [comment]
Done, and the documentation reference is fixed and tested.
