### ISSUE TITLE
Update documentation to reference latest version

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-tool-enonic-ci#7]

**Comment by jsi** [comment]
The latest version is now hardcoded to the latest version, and the release procedure has a new line to make sure the version number is always updated.  However, there are 13 places where the latest version number is used.  This should be replaced with a variable, so it only has to be updated one place.

**Comment by jsi** [comment]
The version has been made into a variable, and the release procedure has been updated to make sure the variable is updated on every release.
