### ISSUE TITLE
Make sure CLI is updated

### ISSUE THREAD

**Issue by rymsha** [enonic/xp-tool-enonic-ci#8]
Probably need to change release procedure

**Comment by jsi** [comment]
The release procedure has been updated, and the release of XP 7.13.4 included CLI 2.7.0, which is currently the latest.

**Comment by jsi** [comment]
Release procedure: https://enonic.atlassian.net/wiki/spaces/ISO/pages/153780227/Procedure+-+Release+XP
Updated code: https://github.com/enonic/enonic-ci-image/blob/master/create_and_push_images.sh
